import { useState, type ReactNode } from 'react'
import { ArrowRight, Camera, CheckCircle2, Clock3, Code2, Crosshair, Eye, Folder, Gamepad2, Maximize2, MessageSquareText, RotateCcw, Send, ShieldCheck, Star, Trash2 } from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import type { ClientState } from '../App'
import type { Account, DashboardData } from '../lib/api'

export function DashboardPanel({ title, children, className = '', action }: { title?: string; children: ReactNode; className?: string; action?: ReactNode }) { return <section className={`dashboard-panel ${className}`}>{title && <header className="panel-heading"><h2>{title}</h2>{action}</header>}{children}</section> }
function StatCard({ icon: Icon, label, value, trend, helper }: { icon: LucideIcon; label: string; value: string; trend: string; helper: string }) { return <article className="stat-card"><Icon className="stat-icon" size={39} strokeWidth={2.35} /><div><p>{label}</p><div className="stat-value"><strong>{value}</strong>{trend && <span className="trend">↑ {trend}</span>}</div><small>{helper}</small></div></article> }
const statsFor = (data: DashboardData) => [{ icon: Clock3, label: 'Play Time', value: `${Math.floor(Number(data.statistics.playTime) / 3600)}h`, trend: '', helper: 'Total play time' }, { icon: Gamepad2, label: 'Sessions', value: String(data.statistics.sessions), trend: '', helper: 'Total sessions' }, { icon: Crosshair, label: 'Blocks Travelled', value: Intl.NumberFormat('en', { notation: 'compact', maximumFractionDigits: 2 }).format(data.statistics.blocksTravelled), trend: '', helper: 'Total distance' }, { icon: Star, label: 'Macros Used', value: Intl.NumberFormat('en').format(data.statistics.macrosUsed), trend: '', helper: 'Across all sessions' }]
function ActionButton({ icon: Icon, children, onClick, disabled }: { icon: LucideIcon; children: ReactNode; onClick?: () => void; disabled?: boolean }) { return <button className="control-button" onClick={onClick} disabled={disabled} type="button"><Icon size={19} />{children}</button> }
function Activity({ text, detail, time }: { text: string; detail: string; time: string }) { return <div className="activity-item"><span className="activity-icon"><CheckCircle2 size={16} /></span><span>{text}</span><a href="#activity">{detail}</a><time>{time}</time></div> }
function formatActivity(type: string) { return type.replaceAll('_', ' ').toLowerCase().replace(/^./, (character) => character.toUpperCase()) }

type DashboardProps = { data: DashboardData; account: Account; username: string; clientState: ClientState; onCommand: (type: string, payload?: unknown) => Promise<void>; onNavigate: (page: string) => void }
export function Dashboard({ data, account, username, clientState, onCommand, onNavigate }: DashboardProps) {
  const [message, setMessage] = useState(''); const [notice, setNotice] = useState('')
  const connected = clientState === 'connected'; const initial = username.trim().charAt(0).toUpperCase() || 'K'
  const clientSince = new Date(account.user.createdAt).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }); const favoriteServer = data.client.serverAddress ?? 'Not connected'
  const runCommand = async (label: string, type: string, payload?: unknown) => { try { await onCommand(type, payload); setNotice(`${label} sent`); window.setTimeout(() => setNotice(''), 2200) } catch (error) { setNotice(error instanceof Error ? error.message : `${label} failed`) } }
  const submitChat = () => { const trimmed = message.trim(); if (!trimmed) return; void runCommand('Message', 'SEND_CHAT', { message: trimmed }).then(() => setMessage('')) }
  return <div className="dashboard-wrap">{notice && <div className="toast" role="status"><CheckCircle2 size={17} />{notice}</div>}<section className="dashboard-surface"><div className="dashboard-content">
    <section className="welcome-banner"><div className="welcome-copy"><p>Welcome back,</p><h1>{username}</h1><span>Same game. More possibilities.</span></div><blockquote>“It's not a client.<br />It's a new way to play.”<cite>— KAIROKK</cite></blockquote></section>
    <div className="stats-grid">{statsFor(data).map((stat) => <StatCard key={stat.label} {...stat} />)}</div>
    <div className="dashboard-main-grid"><DashboardPanel title="Client Control" className="client-control-panel" action={<span className={`connection-label ${connected ? '' : 'offline'}`}><i />{connected ? 'Connected' : clientState === 'reconnecting' ? 'Connecting' : 'Offline'}</span>}><div className="client-control-grid">
      <div className="live-view" aria-label="Live Minecraft client preview"><div className="live-badges"><span><i />Live View</span><span>240 FPS</span></div><button type="button" aria-label="Expand live view"><Maximize2 size={18} /></button><div className="pixel-sun" /><div className="pixel-hills" /><div className="pixel-ground" /></div>
      <div className="control-actions"><ActionButton icon={Camera} disabled={!connected} onClick={() => void runCommand('Screenshot', 'TAKE_SCREENSHOT')}>Screenshot</ActionButton><ActionButton icon={RotateCcw} onClick={() => window.location.reload()}>Reconnect</ActionButton><ActionButton icon={MessageSquareText} disabled={!connected} onClick={() => document.querySelector<HTMLInputElement>('.chat-input')?.focus()}>Send Chat</ActionButton><ActionButton icon={Trash2} onClick={() => setMessage('')}>Clear Chat</ActionButton><ActionButton icon={Eye} disabled={!connected} onClick={() => void runCommand('HUD toggle', 'TOGGLE_HUD')}>Toggle HUD</ActionButton><ActionButton icon={ShieldCheck} disabled>Unload Client</ActionButton><form className="chat-compose" onSubmit={(event) => { event.preventDefault(); submitChat() }}><input className="chat-input" value={message} onChange={(event) => setMessage(event.target.value)} placeholder="Type a message..." aria-label="Chat message" disabled={!connected} /><button type="submit" aria-label="Send message" disabled={!connected || !message.trim()}><Send size={23} fill="currentColor" /></button></form></div>
    </div></DashboardPanel></div></div><aside className="right-rail"><DashboardPanel title="Account" className="account-card"><div className="account-summary"><span className="avatar avatar-large">{initial}</span><div><strong>{username}</strong><span><Star size={16} fill="currentColor" />{account.user.role === 'USER' ? 'Premium' : account.user.role}</span></div></div><dl className="account-details"><div><dt><Clock3 size={17} />Client Since</dt><dd>{clientSince}</dd></div><div><dt><Clock3 size={17} />Total Playtime</dt><dd>{Math.floor(Number(data.statistics.playTime) / 3600)}h</dd></div><div><dt><Folder size={17} />Configs</dt><dd>{data.configs}</dd></div><div><dt><Code2 size={17} />Scripts</dt><dd>{data.scripts}</dd></div><div><dt><ShieldCheck size={17} />Favourite Server</dt><dd title={favoriteServer}>{favoriteServer}</dd></div></dl><button className="manage-account" type="button" onClick={() => onNavigate('Account')}>Manage Account <ArrowRight size={18} /></button></DashboardPanel>
      <DashboardPanel title="Recent Activity" className="account-activity" action={<button className="panel-link" type="button" onClick={() => onNavigate('Statistics')}>View All <ArrowRight size={16} /></button>}><div className="activity-list">{data.activity.slice(0, 4).map((event) => <Activity key={event.id} text={formatActivity(event.type)} detail={event.type === 'REMOTE_COMMAND' ? 'Client command' : 'Kairokk'} time={new Date(event.createdAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })} />)}{data.activity.length === 0 && <div className="empty-state">No recent activity yet.</div>}</div></DashboardPanel>
    </aside></section></div>
}
