import { useState, type ReactNode } from 'react'
import { Activity, Bell, Camera, Check, ChevronRight, Clock3, Eye, Gamepad2, Gauge, KeyRound, Laptop, LockKeyhole, MessageSquareText, Monitor, Radio, RefreshCw, RotateCcw, Send, ShieldCheck, Sparkles, UserRound, Zap } from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import { api, type Account, type DashboardData } from '../lib/api'
import { DashboardPanel } from './Dashboard'

function PageHeader({ eyebrow, title, copy, children }: { eyebrow: string; title: string; copy: string; children?: ReactNode }) { return <header className="inner-page-header"><div><span>{eyebrow}</span><h1>{title}</h1><p>{copy}</p></div>{children}</header> }
function PageMetric({ icon: Icon, label, value, helper }: { icon: LucideIcon; label: string; value: string; helper: string }) { return <article className="page-metric"><span><Icon size={22} /></span><div><small>{label}</small><strong>{value}</strong><p>{helper}</p></div></article> }
function EmptyLine({ children }: { children: ReactNode }) { return <div className="polished-empty"><Sparkles size={18} /><span>{children}</span></div> }

function StatisticsPage({ data }: { data: DashboardData }) {
  const values = [Number(data.statistics.playTime) / 3600, data.statistics.sessions, data.statistics.blocksTravelled, data.statistics.macrosUsed]
  const max = Math.max(1, ...values)
  const activityCounts = data.activity.reduce<Record<string, number>>((counts, event) => { const key = event.type.replaceAll('_', ' '); counts[key] = (counts[key] ?? 0) + 1; return counts }, {})
  return <div className="inner-page statistics-page"><PageHeader eyebrow="PERFORMANCE OVERVIEW" title="Statistics" copy="A clear view of your playtime, movement, sessions, and client activity." />
    <section className="page-metric-grid"><PageMetric icon={Clock3} label="Total Playtime" value={`${Math.floor(values[0])}h`} helper="Recorded across all sessions" /><PageMetric icon={Gamepad2} label="Sessions" value={String(values[1])} helper="Minecraft sessions tracked" /><PageMetric icon={Activity} label="Blocks Travelled" value={Intl.NumberFormat('en', { notation: 'compact' }).format(values[2])} helper="Total movement distance" /><PageMetric icon={Zap} label="Macros Used" value={Intl.NumberFormat('en').format(values[3])} helper="Actions across all sessions" /></section>
    <section className="statistics-layout"><DashboardPanel title="Lifetime Overview" action={<span className="panel-chip">All time</span>}><div className="metric-bars">{[['Playtime', values[0], `${Math.floor(values[0])} hours`], ['Sessions', values[1], `${values[1]} total`], ['Distance', values[2], `${Intl.NumberFormat('en').format(values[2])} blocks`], ['Macros', values[3], `${Intl.NumberFormat('en').format(values[3])} used`]].map(([label, value, detail]) => <div className="metric-bar" key={String(label)}><div><strong>{label}</strong><span>{detail}</span></div><i><b style={{ width: `${Math.max(Number(value) ? 7 : 0, Number(value) / max * 100)}%` }} /></i></div>)}</div></DashboardPanel>
      <DashboardPanel title="Account Pulse" className="pulse-panel"><div className="pulse-ring"><div><Gauge size={29} /><strong>{data.activity.length}</strong><span>recent events</span></div></div><p>{data.activity.length ? 'Kairokk is receiving activity from your account.' : 'Activity will appear as you use Kairokk.'}</p></DashboardPanel>
      <DashboardPanel title="Recent Activity Breakdown" className="activity-breakdown">{Object.entries(activityCounts).length ? <div className="breakdown-list">{Object.entries(activityCounts).map(([label, count], index) => <div key={label}><span className={`breakdown-dot tint-${index % 4}`} /><strong>{label.toLowerCase().replace(/^./, (letter) => letter.toUpperCase())}</strong><em>{count}</em></div>)}</div> : <EmptyLine>No activity has been reported yet.</EmptyLine>}</DashboardPanel>
      <DashboardPanel title="Session Insights" className="insight-panel"><div className="insight-grid"><div><span>Average session</span><strong>{data.statistics.sessions ? `${Math.round(values[0] * 60 / data.statistics.sessions)}m` : '—'}</strong></div><div><span>Blocks per session</span><strong>{data.statistics.sessions ? Intl.NumberFormat('en', { notation: 'compact' }).format(values[2] / data.statistics.sessions) : '—'}</strong></div><div><span>Macros per session</span><strong>{data.statistics.sessions ? Math.round(values[3] / data.statistics.sessions) : '—'}</strong></div></div></DashboardPanel>
    </section></div>
}

function RemoteControlPage({ data, refresh }: { data: DashboardData; refresh: () => Promise<void> }) {
  const [message, setMessage] = useState(''); const [feedback, setFeedback] = useState(''); const offline = data.client.status !== 'ONLINE'
  const command = async (type: string, payload: unknown = {}) => { if (offline) return setFeedback('Minecraft is offline. Connect the client to use remote controls.'); try { await api.command(type, payload); setFeedback(`${type.replaceAll('_', ' ').toLowerCase()} sent successfully.`); await refresh() } catch (error) { setFeedback(error instanceof Error ? error.message : 'Command failed.') } }
  const sendChat = () => { const value = message.trim(); if (!value) return; void command('SEND_CHAT', { message: value }).then(() => setMessage('')) }
  return <div className="inner-page remote-page"><PageHeader eyebrow="LIVE CLIENT LINK" title="Remote Control" copy="Control your connected Minecraft client without leaving the dashboard."><span className={`hero-status ${offline ? 'offline' : ''}`}><i />{offline ? 'Client offline' : 'Live connection'}</span></PageHeader>
    <section className="remote-layout"><DashboardPanel title="Client View" className="remote-view-panel" action={<span className={`connection-label ${offline ? 'offline' : ''}`}><i />{data.client.status}</span>}><div className="remote-screen"><div className="remote-screen-top"><span><Radio size={14} />LIVE VIEW</span><em>{data.client.version ?? 'Awaiting client'}</em></div><div className="remote-landscape"><i /><b /><span /></div><div className="remote-screen-center"><Monitor size={42} /><strong>{offline ? 'Client not connected' : data.client.serverAddress ?? 'Minecraft connected'}</strong><small>{offline ? 'Launch Kairokk in Minecraft to begin streaming.' : 'Game surface only · Private connection'}</small></div></div></DashboardPanel>
      <DashboardPanel title="Connection" className="connection-panel"><dl className="connection-facts"><div><dt>Status</dt><dd className={offline ? 'danger' : 'success'}>{data.client.status}</dd></div><div><dt>Client version</dt><dd>{data.client.version ?? '—'}</dd></div><div><dt>Current server</dt><dd>{data.client.serverAddress ?? '—'}</dd></div><div><dt>Stream quality</dt><dd>Balanced</dd></div></dl><button className="primary-page-button" type="button" onClick={() => window.location.reload()}><RefreshCw size={17} />Refresh connection</button></DashboardPanel>
      <DashboardPanel title="Quick Controls" className="remote-controls"><div className="command-grid"><button disabled={offline} onClick={() => void command('TAKE_SCREENSHOT')}><Camera /><span><strong>Screenshot</strong><small>Capture the game</small></span><ChevronRight /></button><button disabled={offline} onClick={() => void command('TOGGLE_HUD')}><Eye /><span><strong>Toggle HUD</strong><small>Show or hide overlay</small></span><ChevronRight /></button><button disabled={offline} onClick={() => document.querySelector<HTMLInputElement>('.remote-chat-input')?.focus()}><MessageSquareText /><span><strong>Send chat</strong><small>Message in-game</small></span><ChevronRight /></button><button onClick={() => window.location.reload()}><RotateCcw /><span><strong>Reconnect</strong><small>Refresh the client link</small></span><ChevronRight /></button></div></DashboardPanel>
      <DashboardPanel title="Minecraft Chat" className="remote-chat-panel"><div className="chat-history"><MessageSquareText size={25} /><strong>Remote chat</strong><span>{offline ? 'Connect the client to send messages.' : 'Messages are delivered directly to your game.'}</span></div><form className="remote-chat-form" onSubmit={(event) => { event.preventDefault(); sendChat() }}><input className="remote-chat-input" value={message} onChange={(event) => setMessage(event.target.value)} placeholder="Type a message..." disabled={offline} /><button disabled={offline || !message.trim()}><Send size={19} /></button></form></DashboardPanel>
    </section>{feedback && <div className="page-feedback" role="status"><Check size={16} />{feedback}</div>}</div>
}

function AccountPage({ account, refresh }: { account: Account; refresh: () => Promise<void> }) {
  const [username, setUsername] = useState(account.user.username); const [currentPassword, setCurrentPassword] = useState(''); const [newPassword, setNewPassword] = useState(''); const [feedback, setFeedback] = useState('')
  const save = async () => { try { await api.updateAccount({ username, ...(newPassword ? { currentPassword, newPassword } : {}) }); await refresh(); setCurrentPassword(''); setNewPassword(''); setFeedback('Account changes saved.') } catch (error) { setFeedback(error instanceof Error ? error.message : 'Could not save your account.') } }
  const initial = account.user.username.charAt(0).toUpperCase()
  return <div className="inner-page account-page"><PageHeader eyebrow="ACCOUNT CENTRE" title="Your Account" copy="Manage your profile, security, devices, and active sessions." />
    <section className="account-page-layout"><DashboardPanel className="profile-card"><div className="profile-identity"><span className="avatar profile-avatar">{initial}</span><div><h2>{account.user.username}</h2><p>{account.user.email}</p><span><Sparkles size={14} />{account.user.role === 'USER' ? 'Premium member' : account.user.role}</span></div></div><div className="profile-facts"><div><small>Member since</small><strong>{new Date(account.user.createdAt).toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' })}</strong></div><div><small>Connected client</small><strong>{account.client.version ?? 'Not connected'}</strong></div><div><small>Active sessions</small><strong>{account.sessions.length}</strong></div></div></DashboardPanel>
      <DashboardPanel title="Profile Details" className="account-form-card"><form onSubmit={(event) => { event.preventDefault(); void save() }}><label><span>Username</span><div><UserRound size={17} /><input value={username} onChange={(event) => setUsername(event.target.value)} /></div></label><label><span>Email address</span><div className="disabled-field"><MessageSquareText size={17} /><input value={account.user.email} disabled /></div></label><button className="primary-page-button" disabled={username === account.user.username} type="submit">Save profile</button></form></DashboardPanel>
      <DashboardPanel title="Security" className="security-card"><form onSubmit={(event) => { event.preventDefault(); void save() }}><label><span>Current password</span><div><LockKeyhole size={17} /><input type="password" value={currentPassword} onChange={(event) => setCurrentPassword(event.target.value)} placeholder="Required to change password" /></div></label><label><span>New password</span><div><KeyRound size={17} /><input type="password" value={newPassword} onChange={(event) => setNewPassword(event.target.value)} placeholder="12 characters minimum" /></div></label><button className="primary-page-button" disabled={!currentPassword || newPassword.length < 12} type="submit">Update password</button></form></DashboardPanel>
      <DashboardPanel title="Authorized Devices" className="device-card">{account.devices.length ? <div className="device-list">{account.devices.map((device) => <div key={device.id}><span><Laptop size={21} /></span><div><strong>{device.deviceName}</strong><small>{device.platform} · Last seen {new Date(device.lastSeenAt).toLocaleString()}</small></div><em>Authorized</em></div>)}</div> : <EmptyLine>No authorized devices yet.</EmptyLine>}</DashboardPanel>
      <DashboardPanel title="Session Security" className="sessions-card"><div className="security-callout"><ShieldCheck size={27} /><div><strong>{account.sessions.length} active {account.sessions.length === 1 ? 'session' : 'sessions'}</strong><span>Sign out other browsers if you do not recognize recent activity.</span></div></div><button className="secondary-page-button" type="button" onClick={() => void api.revokeOthers().then(() => { setFeedback('Other sessions signed out.'); return refresh() })}>Sign out other sessions</button></DashboardPanel>
    </section>{feedback && <div className="page-feedback" role="status"><Check size={16} />{feedback}</div>}</div>
}

type Preferences = { notifications: boolean; motion: boolean; privateMode: boolean; positionSharing: boolean; quality: string }
const defaults: Preferences = { notifications: true, motion: true, privateMode: true, positionSharing: false, quality: 'balanced' }
const initialPreferences = (): Preferences => { try { return { ...defaults, ...JSON.parse(localStorage.getItem('kairokk_dashboard_preferences') ?? '{}') } } catch { return defaults } }
function SettingsPage() {
  const [preferences, setPreferences] = useState<Preferences>(initialPreferences); const [saved, setSaved] = useState(false)
  const update = <K extends keyof Preferences>(key: K, value: Preferences[K]) => { const next = { ...preferences, [key]: value }; setPreferences(next); localStorage.setItem('kairokk_dashboard_preferences', JSON.stringify(next)); setSaved(true); window.setTimeout(() => setSaved(false), 1600) }
  const toggleRows: { key: keyof Pick<Preferences, 'notifications' | 'motion' | 'privateMode' | 'positionSharing'>; icon: LucideIcon; title: string; copy: string }[] = [{ key: 'notifications', icon: Bell, title: 'Dashboard notifications', copy: 'Show client and account activity alerts.' }, { key: 'motion', icon: Sparkles, title: 'Interface motion', copy: 'Use hover movement and animated ambient orbs.' }, { key: 'privateMode', icon: ShieldCheck, title: 'Privacy mode', copy: 'Keep sensitive client details hidden by default.' }, { key: 'positionSharing', icon: Radio, title: 'Position sharing', copy: 'Allow the connected client to report coordinates.' }]
  return <div className="inner-page settings-page"><PageHeader eyebrow="DASHBOARD PREFERENCES" title="Settings" copy="Tune how Kairokk looks, behaves, and communicates with your client." />
    <section className="settings-layout"><DashboardPanel title="General" className="settings-group"><div className="settings-list">{toggleRows.slice(0, 2).map(({ key, icon: Icon, title, copy }) => <div className="setting-row" key={key}><span><Icon size={20} /></span><div><strong>{title}</strong><small>{copy}</small></div><button className={`toggle ${preferences[key] ? 'toggle-on' : ''}`} onClick={() => update(key, !preferences[key])} aria-label={`${title} ${preferences[key] ? 'enabled' : 'disabled'}`} aria-pressed={preferences[key]}><i /></button></div>)}</div></DashboardPanel>
      <DashboardPanel title="Privacy & Client" className="settings-group"><div className="settings-list">{toggleRows.slice(2).map(({ key, icon: Icon, title, copy }) => <div className="setting-row" key={key}><span><Icon size={20} /></span><div><strong>{title}</strong><small>{copy}</small></div><button className={`toggle ${preferences[key] ? 'toggle-on' : ''}`} onClick={() => update(key, !preferences[key])} aria-label={`${title} ${preferences[key] ? 'enabled' : 'disabled'}`} aria-pressed={preferences[key]}><i /></button></div>)}</div></DashboardPanel>
      <DashboardPanel title="Remote Stream" className="stream-settings"><div className="stream-setting-copy"><span><Monitor size={23} /></span><div><strong>Preferred quality</strong><small>Higher quality uses more bandwidth when remote view is active.</small></div></div><div className="quality-picker">{['low', 'balanced', 'high'].map((quality) => <button key={quality} className={preferences.quality === quality ? 'selected' : ''} onClick={() => update('quality', quality)}>{quality}<span>{quality === 'low' ? '480p' : quality === 'balanced' ? '720p' : '1080p'}</span></button>)}</div></DashboardPanel>
      <DashboardPanel title="About Kairokk" className="about-settings"><div className="about-logo"><img src="/kairokk-logo.png" alt="" /><div><strong>KAIROKK</strong><span>CONTROL BEYOND LIMITS.</span></div></div><dl><div><dt>Dashboard</dt><dd>v1.0.0</dd></div><div><dt>Connection protocol</dt><dd>v1</dd></div><div><dt>Update channel</dt><dd>Stable</dd></div></dl></DashboardPanel>
    </section>{saved && <div className="page-feedback" role="status"><Check size={16} />Preference saved</div>}</div>
}

export function OperationalPage({ page, data, account, refresh }: { page: string; data: DashboardData; account: Account; refresh: () => Promise<void> }) {
  if (page === 'Statistics') return <StatisticsPage data={data} />
  if (page === 'Remote Control') return <RemoteControlPage data={data} refresh={refresh} />
  if (page === 'Account') return <AccountPage account={account} refresh={refresh} />
  if (page === 'Settings') return <SettingsPage />
  return <div className="inner-page"><PageHeader eyebrow="KAIROKK" title={page} copy="This workspace is ready for your client data." /><DashboardPanel><EmptyLine>No data has been reported for this page yet.</EmptyLine></DashboardPanel></div>
}
